// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUwu0L9XMhjp9ZxSrCwiXnIey8HBK0kdU',
    appId: '1:1057229189967:web:0b5de728582f0299cc4b3a',
    messagingSenderId: '1057229189967',
    projectId: 'flutter-push-notificatio-bee4c',
    authDomain: 'flutter-push-notificatio-bee4c.firebaseapp.com',
    databaseURL: 'https://flutter-push-notificatio-bee4c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-push-notificatio-bee4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi43ntpTx3Mk6mVH3Jo2kuSWXfG182iBo',
    appId: '1:1057229189967:android:8eb1ca6e527774a0cc4b3a',
    messagingSenderId: '1057229189967',
    projectId: 'flutter-push-notificatio-bee4c',
    databaseURL: 'https://flutter-push-notificatio-bee4c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-push-notificatio-bee4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilLm6WiPRd5SNhudIH8BiseQF__CqXTA',
    appId: '1:1057229189967:ios:0f2f8bb22d2e48b2cc4b3a',
    messagingSenderId: '1057229189967',
    projectId: 'flutter-push-notificatio-bee4c',
    databaseURL: 'https://flutter-push-notificatio-bee4c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-push-notificatio-bee4c.firebasestorage.app',
    iosBundleId: 'com.example.pushChatNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilLm6WiPRd5SNhudIH8BiseQF__CqXTA',
    appId: '1:1057229189967:ios:0f2f8bb22d2e48b2cc4b3a',
    messagingSenderId: '1057229189967',
    projectId: 'flutter-push-notificatio-bee4c',
    databaseURL: 'https://flutter-push-notificatio-bee4c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-push-notificatio-bee4c.firebasestorage.app',
    iosBundleId: 'com.example.pushChatNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUwu0L9XMhjp9ZxSrCwiXnIey8HBK0kdU',
    appId: '1:1057229189967:web:6d14d6e1f7cef165cc4b3a',
    messagingSenderId: '1057229189967',
    projectId: 'flutter-push-notificatio-bee4c',
    authDomain: 'flutter-push-notificatio-bee4c.firebaseapp.com',
    databaseURL: 'https://flutter-push-notificatio-bee4c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-push-notificatio-bee4c.firebasestorage.app',
  );

}