name: CI/CD with Firebase App Distribution

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is named 'main'

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Flutter environment
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    # Install Flutter dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build the Flutter app (APK for Android)
    - name: Build Flutter APK
      run: flutter build apk --release

    # Install Firebase CLI
    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash

    # Upload APK to Firebase App Distribution
    # testtt
    - name: Upload APK to Firebase
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app $ANDROID_APP_ID \
          --groups testers
